---
- name: A simple user setup
  hosts: 192.168.6.15
  become: true
  tasks: 
   - name: Add users
     user: 
      name: Fred
      uid: 1020
      state: present

   - name: Make a directory
     file: 
      path: /home/dir.txt
      state: directory



