---
- name: Configuration of webserver
  hosts: 127.0.0.1
  become: false
  tasks: 
   - name: Install the http package.
     yum:
      name:
       - httpd
       - firewalld
       - mariadb-server
      state: latest
     when: ansible_distribution == 'RedHat'

   - name: Enable the http service is running 
     service: 
      name: httpd
      enabled: true
      state: started

   - name: Enable firewall service and start
     service:
      service: firewalld
      state: started
      enabled: true

   - name: Print the output
     stat:    
      path: /home
     register: Webserver

   - name: Display the content
     copy:
      content: "Hello World from Ansibull. \n"
      dest: /var/www/html/index.html
     
   - name: The print output
     debug: 
      var: Webserver

#the /etc/hosts is used to input the hostname and the ip address of the managed hosts on which the webserver is to be configured. Here we used the RedHat OS yum module. 
