---
- name: Configuration of webserver
  hosts: 127.0.0.1
  become: false
  tasks: 
   - name: Install the http package.
     ansible.builtin.package:
      name:
       - httpd
       - firewalld
      state: latest
     when: ansible_distribution == 'RedHat'

   - name: Enable the http service is running 
     asible.builtin.service: 
      name: httpd
      enabled: true
      state: started

   - name: Enable firewall service and start
     ansible.builtin.service:
      service: firewalld
      state: started
      enabled: true

   - name: Enable the firewalld service port
     ansible.posix.firewalld:
      service: https
      state: enabled
      immediate: true
      permanent: true

   - name: Print the output
     stat: 
      path: /
      state: present
     register: Webserver setup running

   - name: The print output
     debug: 
      var: Webserver setup running

#the /etc/hosts is used to input the hostname and the ip address of the managed hosts on which the webserver is to be configured. Here we used the RedHat OS yum module. 
